export const initialValues = {
  officeAddress: "",
  officeCity: "",
  officeCountry: "",
  officeZip: "",
  legalForm: "",
  legalName: "",
  legalAddress: "",
  legalCity: "",
  legalCountry: "",
  legalZip: "",
  legalRegistrationNumber: "",
  legalVATNumber: "",
  registrationNumber: "",
};
