export const initialValues = {
  officeAddress: "",
  officeCity: "",
  officeCountry: "",
  officeZip: "",
  legalForm: "",
  legalName: "",
  legalRegistrationNumber: "",
  legalVATNumber: "",
  registrationNumber: "",
  address: "",
  city: "",
  country: "",
  zip: "",
};
