export const PATHS = {
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  NEW_EVENT: "/new",
  EVENTS: "/events",
  EVENT: "/events/:id",
  EVENT_EDIT: "/events/:id/edit",
  PRODUCTS: "/products",
  LOGIN: "/login",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  FORGET_PASSWORD: "/forget-password",
  SIGN_UP: "/sign-up/",
  CONFIRM_MAIL: "/confirm-email",
  CONFIRM_SMS: "/confirm-sms",
  ONBOARDING_LEGAL_FORM_CHOICE: "/onboarding/legal-form",
  ONBOARDING_COMPANY: "/onboarding/company",
  ONBOARDING_COMPANY_SEARCH: "/onboarding/company/search",
  ONBOARDING_PERFORMER: "/onboarding/performer",
  ONBOARDING_OFFICE: "/onboarding/office",
  ONBOARDING_INTERMITTENT: "/onboarding/intermittent",
};
